Models/BookModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Bookstore.Models
{
    public class BookModel
    {
        public int ID { get; set; }
        public string author { get; set; }

        [DataType(DataType.Date)]
        public DateTime releaseDate { get; set; }

        public double price { get; set; }
    }
}

Models/BookStoreContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Bookstore.Models
{
    public class BookStoreContext : DbContext
    {
        public BookStoreContext(DbContextOptions<BookStoreContext> options):base(options) {

        }

        public DbSet <Bookstore.Models.BookStoreContext> Book { get; set; } 
    }
}

Models/ErrorViewModel.cs
using System;

namespace Bookstore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserModel.cs
using System;
// using System.Data.
namespace Bookstore.Models
{
    public class UserModel
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string password { get ; set; }
    }

    // public class UserModelDBContext:DbContext 
    // {
    //     public DbSet<UserModel> Users;
    // }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace Bookstore.Controllers
{
    public class AboutController : Controller
    {
        // 
        // GET: /about/Index

        public IActionResult Index()
        {
            return View();
        }

        // 
        // GET: /HelloWorld/getBook/ 

    
    }
}

Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Models;

namespace Bookstore.Controllers
{
    public class BookStoreController : Controller
    {
        private readonly BookStore _context;

        public BookStoreController(BookStore context)
        {
            _context = context;
        }

        // GET: BookStore
        public async Task<IActionResult> Index()
        {
            return View(await _context.BookModel.ToListAsync());
        }

        // GET: BookStore/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookModel = await _context.BookModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (bookModel == null)
            {
                return NotFound();
            }

            return View(bookModel);
        }

        // GET: BookStore/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BookStore/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,author,releaseDate,price")] BookModel bookModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bookModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bookModel);
        }

        // GET: BookStore/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookModel = await _context.BookModel.FindAsync(id);
            if (bookModel == null)
            {
                return NotFound();
            }
            return View(bookModel);
        }

        // POST: BookStore/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,author,releaseDate,price")] BookModel bookModel)
        {
            if (id != bookModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookModelExists(bookModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bookModel);
        }

        // GET: BookStore/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookModel = await _context.BookModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (bookModel == null)
            {
                return NotFound();
            }

            return View(bookModel);
        }

        // POST: BookStore/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookModel = await _context.BookModel.FindAsync(id);
            _context.BookModel.Remove(bookModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookModelExists(int id)
        {
            return _context.BookModel.Any(e => e.ID == id);
        }
    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace Bookstore.Controllers
{
    public class ContactController : Controller
    {
        // 
        // GET: /Contact/Login/

        public IActionResult Login()
        {
            return View();
        }

        // 
        // GET: /Contact/Signup/ 

        public ActionResult Signup()
        {
            return View();
        }

        // public string showLength(string name, int numberOfTimes = 1){
        //     return HtmlEncoder.Default.Encode($"Hello {name}, Number of Times is {numberOfTimes}");
        // }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Bookstore.Models;

namespace Bookstore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact(string name,int times = 1)
        {
            ViewBag.Message = "Hello" + name;
            ViewBag.Times = times;
            return View();
        }

        public IActionResult About(){
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/About/index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Hello from our View Template!</p>

Views/BookStore/Create.cshtml
@model Bookstore.Models.BookModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BookModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="author" class="control-label"></label>
                <input asp-for="author" class="form-control" />
                <span asp-validation-for="author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="releaseDate" class="control-label"></label>
                <input asp-for="releaseDate" class="form-control" />
                <span asp-validation-for="releaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BookStore/Delete.cshtml
@model Bookstore.Models.BookModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.releaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.releaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/BookStore/Details.cshtml
@model Bookstore.Models.BookModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BookModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.releaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.releaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/BookStore/Edit.cshtml
@model Bookstore.Models.BookModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BookModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="author" class="control-label"></label>
                <input asp-for="author" class="form-control" />
                <span asp-validation-for="author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="releaseDate" class="control-label"></label>
                <input asp-for="releaseDate" class="form-control" />
                <span asp-validation-for="releaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BookStore/Index.cshtml
@model IEnumerable<Bookstore.Models.BookModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.releaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.releaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Contact/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<form class="form" method = "post" action = "">
    <h2>Login Page</h2>
    
    <div class="form-group">
        <label for="userName" class="label">UserName</label><br>
        <input type="text" name="username" id="user_id" class="form-control">
    </div>
    <div class="form-group">
        <label for="password" class="label">Password</label>
        <input class="form-control" type="password" name="pass" id="pass_id">
    </div>
    <Button class="btn btn-primary">Submit</Button>
    <a href="https://localhost:5001/Contact/signup"> <strong>Have No Account?</strong> </a>
</form>

Views/Contact/Signup.cshtml
@{
    ViewData["Title"] = "Signup";
}

<form action="" method="post">
    <h1>Signup page</h1>
    <div class="form-group">
        <label for="firstname" class="label">First Name</label>
        <input type="text" name="firstname" id="first_id" class="form-control">
    </div>

    <div class="form-group">
        <label for="lastname" class="label">Last Name</label>
        <input type="text" name="lastname" id="last_id" class="form-control">
    </div>

    <div class="form-group">
        <label for="lastname" class="label">Email</label>
        <input type="email" name="email" id="email_id" class="form-control">
    </div>

    <div class="form-group">
        <label for="password" class="label">Password</label>
        <input type="password" name="password" id="pass_id" class="form-control">
    </div>
    <div class="form-group">
        <label for="confirm" class="label">Confirm Password</label>
        <input type="password" name="confirm" id="confirm_id" class="form-control">
    </div>

    <Button class="btn btn-primary">Create</Button>
    <a href="https://localhost:5001/Contact/login"><strong>Have Account?</strong></a>
</form>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Page";
    ViewData["name"] = "Yonas Alem";
}
<h1>@ViewData["Title"]</h1>
<div class="nav">
    <p>@ViewData["name"]</p>
</div>

<footer>
    This is about page.
</footer>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
    ViewData["statement"] = "Privacy Page ";
}
<h1>@ViewData["Title"]</h1>
<div class="nav">
    <p>@ViewData["statement"]</p>
</div>

<div class="body">
    <ul>
        @for(int i = 0;i < ViewBag.Times; i++){
            <li> @ViewBag.Message</li>
        }
    </ul>
</div>

<p>Use this page to detail your site's privacy policy.</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Login">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2018 - Bookstore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>